### ISSUE TITLE
godbolt example fails with nvc++ 22.2

### ISSUE THREAD

**Issue by rscohn2** [kokkos/mdspan#126] opened 2022-03-03 19:13 UTC
The godbolt examples fails with nvc++
```
rscohn1@antcarcomp01:tests$ /opt/nvidia/hpc_sdk/Linux_x86_64/22.2/compilers/bin/nvc++ mdspan.cpp -std=c++17 -I ../mdspan/include/experimental/
"../mdspan/include/experimental/__p0009_bits/type_list.hpp", line 116: warning: last line of file ends without a newline
  } // end namespace std
                        ^

"mdspan.cpp", line 13: error: no instance of constructor "extents" matches the argument list
            argument types are: (int, int)
    stdex::mdspan m{d.data(), stdex::extents{3, 3}};
                                            ^

"mdspan.cpp", line 13: error: too many initializer values
    stdex::mdspan m{d.data(), stdex::extents{3, 3}};
                                                ^

"mdspan.cpp", line 13: error: no instance of constructor "mdspan" matches the argument list
            argument types are: (int *, <error-type>)
    stdex::mdspan m{d.data(), stdex::extents{3, 3}};
                  ^

3 errors detected in the compilation of "mdspan.cpp".
rscohn1@antcarcomp01:tests$
```

From nvidia hpc sdk 22.2: https://developer.nvidia.com/nvidia-hpc-sdk-downloads

```
rscohn1@antcarcomp01:tests$ /opt/nvidia/hpc_sdk/Linux_x86_64/22.2/compilers/bin/nvc++ --version

nvc++ 22.2-0 64-bit target on x86-64 Linux -tp zen
NVIDIA Compilers and Tools
Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
rscohn1@antcarcomp01:tests$
```

**Comment by rscohn2** [comment] 2022-03-03 20:21
Using explicit types works:

```
#include <mdspan>
#include <iostream>

namespace stdex = std::experimental;

int main() {
  std::array d{
    0, 5, 1,
    3, 8, 4,
    2, 7, 6,
  };

  stdex::mdspan<int, stdex::dextents<2>> m{d.data(), stdex::dextents<2>{3, 3}};

  for (std::size_t i = 0; i < m.extent(0); ++i)
    for (std::size_t j = 0; j < m.extent(1); ++j)
    #if MDSPAN_USE_BRACKET_OPERATOR
      std::cout << "m(" << i << ", " << j << ") == " << m[i, j] << "\n";
    #else
      std::cout << "m(" << i << ", " << j << ") == " << m(i, j) << "\n";
    #endif
}
```

**Comment by rscohn2** [comment] 2022-03-03 20:33
But is still broken for my actual code:

```
rscohn1@antcarcomp01:tests$ /opt/nvidia/hpc_sdk/Linux_x86_64/22.2/compilers/bin/nvc++ mdspan-2.cpp -std=c++17 -I ../mdspan/\
include/experimental/ && ./a.out
"../mdspan/include/experimental/__p0009_bits/type_list.hpp", line 116: warning: last line of file ends without a newline
  } // end namespace std
                        ^

ext.extent(0): 10
ext.extent(1): 0
  expected: 10
rscohn1@antcarcomp01:tests$
```

Here it is:

```
#include <mdspan>
#include <iostream>

namespace stdex = std::experimental;

constexpr size_t dim = 10;

int main() {
  stdex::dextents<2> ext(dim, dim);
  std::cout << "ext.extent(0): " << ext.extent(0) << "\n";
  std::cout << "ext.extent(1): " << ext.extent(1) << "\n";
  std::cout << "  expected: " << dim << "\n";
}
```

**Comment by rscohn2** [comment] 2022-03-03 20:35
Something about the constexpr breaks it because this works:

```
#include <mdspan>
#include <iostream>

namespace stdex = std::experimental;

size_t dim = 10;

int main() {
  stdex::dextents<2> ext(dim, dim);
  std::cout << "ext.extent(0): " << ext.extent(0) << "\n";
  std::cout << "ext.extent(1): " << ext.extent(1) << "\n";
  std::cout << "  expected: " << dim << "\n";
}
```

output:

```
rscohn1@antcarcomp01:tests$ /opt/nvidia/hpc_sdk/Linux_x86_64/22.2/compilers/bin/nvc++ mdspan-2.cpp -std=c++17 -I ../mdspan/\
include/experimental/ && ./a.out
"../mdspan/include/experimental/__p0009_bits/type_list.hpp", line 116: warning: last line of file ends without a newline
  } // end namespace std
                        ^

ext.extent(0): 10
ext.extent(1): 10
  expected: 10
rscohn1@antcarcomp01:tests$
```

**Comment by crtrott** [comment] 2022-04-05 23:39
Sorry overlooked this coming in. We can take a look. nvc++ and nvcc sometimes have unique issues since they use edg which none of the other compilers do.  @brycelelbach any idea? I can try reproduce it myself too.

**Comment by brycelelbach** [comment] 2022-04-06 13:37
I'll ask someone to look at this.

**Comment by mhoemmen** [comment] 2022-06-17 21:21
@brycelelbach @crtrott I tested nvc++ (from the most recent NVHPC 22.5 release) with the mdspan-0.3.0 tag (before the most recent breaking changes to mdspan; see https://github.com/kokkos/mdspan/issues/136) and the following configuration.
```
cmake $HOME/src/kokkos/mdspan \
      -DCMAKE_CXX_COMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/22.5/compilers/bin/nvc++ \
      -DCMAKE_INSTALL_PREFIX=$HOME/pkg/kokkos/mdspan-nvcpp \
      -DMDSPAN_ENABLE_TESTS=ON \
      -DMDSPAN_ENABLE_EXAMPLES=ON \
      -DMDSPAN_CXX_STANDARD=17
```
I got to `test_contiguous_layouts.cpp` and then my terminal blew up with error messages starting like the following:
```
[ 27%] Building CXX object tests/CMakeFiles/test_contiguous_layouts.dir/test_contiguous_layouts.cpp.o
"/home/mhoemmen/src/kokkos/mdspan/include/experimental/__p0009_bits/layout_left.hpp", line 148: warning: pointless comparison of unsigned integer with zero
         for(size_type r=0; r<__extents.rank(); r++) {
                             ^
          detected during:
            instantiation of "std::experimental::layout_left::mapping<Extents>::mapping(const OtherMapping &) [with Extents=std::experimental::extents<>, OtherMapping=std::experimental::layout_stride::mapping<std::experimental::extents<>>, <unnamed>=0]" at line 366 of "/home/mhoemmen/src/kokkos/mdspan/tests/test_contiguous_layouts.cpp"
            instantiation of "void TestLayoutConversion_implicit_conversion_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_=std::tuple<std::experimental::layout_left, std::experimental::layout_stride, std::experimental::extents<>, std::experimental::extents<>, std::integer_sequence<std::size_t>, std::integral_constant<bool, true>>]" at line 469 of "/home/mhoemmen/bld/kokkos/mdspan-nvcpp/tests/googletest-src/googletest/include/gtest/internal/gtest-internal.h"
            implicit generation of "TestLayoutConversion_implicit_conversion_Test<gtest_TypeParam_>::~TestLayoutConversion_implicit_conversion_Test() noexcept [with gtest_TypeParam_=std::tuple<std::experimental::layout_left, std::experimental::layout_stride, std::experimental::extents<>, std::experimental::extents<>, std::integer_sequence<std::size_t>, std::integral_constant<bool, true>>]" at line 469 of "/home/mhoemmen/bld/kokkos/mdspan-nvcpp/tests/googletest-src/googletest/include/gtest/internal/gtest-internal.h"
            instantiation of class "TestLayoutConversion_implicit_conversion_Test<gtest_TypeParam_> [with gtest_TypeParam_=std::tuple<std::experimental::layout_left, std::experimental::layout_stride, std::experimental::extents<>, std::experimental::extents<>, std::integer_sequence<std::size_t>, std::integral_constant<bool, true>>]" at line 469 of "/home/mhoemmen/bld/kokkos/mdspan-nvcpp/tests/googletest-src/googletest/include/gtest/internal/gtest-internal.h"
            implicit generation of "TestLayoutConversion_implicit_conversion_Test<gtest_TypeParam_>::TestLayoutConversion_implicit_conversion_Test() [with gtest_TypeParam_=std::tuple<std::experimental::layout_left, std::experimental::layout_stride, std::experimental::extents<>, std::experimental::extents<>, std::integer_sequence<std::size_t>, std::integral_constant<bool, true>>]" at line 469 of "/home/mhoemmen/bld/kokkos/mdspan-nvcpp/tests/googletest-src/googletest/include/gtest/internal/gtest-internal.h"
            [ 63 instantiation contexts not shown ]
            instantiation of "bool testing::internal::TypeParameterizedTest<Fixture, TestSel, Types>::Register(const char *, const testing::internal::CodeLocation &, const char *, const char *, int, const std::vector<std::__cxx11::string, std::allocator<std::__cxx11::string>> &) [with Fixture=TestLayoutConversion, TestSel=testing::internal::TemplateSel<TestLayoutConversion_implicit_conversion_Test>, Types=testing::internal::Types<std::tuple<std::experimental::layout_left, std::experimental::layout_left, std::experimental::extents<18446744073709551615UL, 18446744073709551615UL>, std::experimental::extents<5UL, 18446744073709551615UL>, std::integer_sequence<size_t, 5UL, 0UL>, std::integral_constant<bool, true>>, std::tuple<std::experimental::layout_left, std::experimental::layout_left, std::experimental::extents<18446744073709551615UL, 10UL>, std::experimental::extents<5UL, 10UL>, std::integer_sequence<size_t, 5UL, 10UL>, std::integral_constant<bool, true>>, std::tuple<std::experimental::layout_left, std::experimental::layout_left, std::experimental::extents<5UL, 18446744073709551615UL>, std::experimental::extents<5UL, 10UL>, std::integer_sequence<size_t, 5UL, 10UL>, std::integral_constant<bool, true>>, std::tuple<std::experimental::layout_left, std::experimental::layout_left, std::experimental::extents<5UL, 18446744073709551615UL>, std::experimental::extents<5UL, 18446744073709551615UL>, std::integer_sequence<size_t, 5UL, 10UL>, std::integral_constant<bool, true>>, std::tuple<std::experimental::layout_left, std::experimental::layout_left, std::experimental::extents<18446744073709551615UL, 10UL, 15UL, 18446744073709551615UL, 25UL>, std::experimental::extents<5UL, 10UL, 18446744073709551615UL, 20UL, 18446744073709551615UL>, std::integer_sequence<size_t, 5UL, 10UL, 15UL, 20UL, 25UL>, std::integral_constant<bool, false>>, std::tuple<std::experimental::layout_left, std::experimental::layout_left, std::experimental::extents<5UL, 10UL, 15UL, 20UL, 25UL>, std::experimental::extents<5UL, 10UL, 18446744073709551615UL, 20UL, 18446744073709551615UL>, ...
```
and ending with something running out of recursion depth.

**Comment by mhoemmen** [comment] 2022-06-17 21:34
I filed an nvc++ bug and will continue to track there.

**Comment by crtrott** [comment] 2022-07-05 17:48
I think we have nvc++ in general now working or? At least 22.3 and up?

**Comment by mhoemmen** [comment] 2022-07-05 17:58
Yup, I've been testing with nvc++ 22.5.  I specifically fixed the `test_contiguous_layouts.cpp` issue for nvc++ 22.5.

**Comment by crtrott** [comment] 2022-07-05 19:01
Yeah I think we can close this.

**Closed as completed by crtrott** 2022-07-05 19:01 UTC
